---
- name: Run local
  vars:
    azure:
      client_id: '{{ lookup("env", "AZURE_CLIENT_ID") }}'
      secret: '{{ lookup("env", "AZURE_SECRET") }}'
      tenant: '{{ lookup("env", "AZURE_TENANT") }}'
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Login to Azure CLI
      command: az login --service-principal -u {{ azure.client_id }} -p {{ azure.secret }} --tenant {{ azure.tenant }}

    - name: Use Azure CLI to retrieve VM information
      command: az vm list -g xvoscluster-lowbrow-rg
