---
- name: Run local
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Login to Azure CLI
      command: az login --service-principal -u {{ client_id }} -p {{ secret }} --tenant {{ tenant }}

    - name: Use Azure CLI to retrieve VM information
      command: az vm list -g xvoscluster-lowbrow-rg
